package OnlineAuctionPlatform.model.enums;

public enum DocumentType {
    OWNERSHIP_CERTIFICATE,
    VALUATION_REPORT,
    PUBLICATION_NOTICE,
    EXECUTION_CASE_DOCUMENT,
    ID_DOCUMENT,
    COMPANY_REG_CERTIFICATE,
    PROOF_OF_ACCOUNT_OWNERSHIP,
    AUTHORIZATION_LETTER,
    NO_DISPUTE_DECLARATION,
    OTHER
}
